# Site settings
title: *folio
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
url: nrfreudenberg.github.io
baseurl: /recsys
twitter_username: twitter_username
github_username:  nrfreudenberg

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


